### ISSUE TITLE
When soft-wrap is enabled markers in scrollbar do not align with content

### ISSUE THREAD

**Issue by enwi** [surdu/scroll-marker-find#1]
When soft-wrap is enabled markers displayed in the scrollbar are not in line with the content.

See the picture below: 
![unbenannt](https://user-images.githubusercontent.com/25170066/44195213-a992a280-a138-11e8-8d53-ffeb487c4c21.PNG)

**Comment by surdu** [comment]
Thank you for the report, and sorry for the late fix 😞
